---
- name: Download Volatility source
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  get_url:
    url: https://github.com/volatilityfoundation/volatility/archive/{{ volatility_ver }}.tar.gz
    dest: /home/cuckoo/

- name: Uncompress Volatility source
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  unarchive:
    src: /home/cuckoo/volatility-{{ volatility_ver }}.tar.gz
    dest: "{{ build_dir }}"
    remote_src: yes

- name: Build Volatility
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: python setup.py build
  args:
    chdir: "{{ build_dir }}/volatility-{{ volatility_ver }}"

- name: Install Volatility
  become: true
  become_method: sudo
  shell: python setup.py install
  args:
    chdir: "{{ build_dir }}/volatility-{{ volatility_ver }}"
    creates: /bin/vol.py
